version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.6

jobs:
  node/test:
    docker:
      - image: circleci/15.12.0-stretch
    steps:
      - checkout
      - restore_cache:
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
  node-tests:
    jobs:
      - node/test
      - deploy:
          requires:
            - node/test
          filters:
            branches:
              only: main
